export const TOGGLE_FETCHING_INVESTMENTS = 'TOGGLE_FETCHING_INVESTMENTS';

export const FETCH_INVESTMENTS_SUCCESS = 'FETCH_INVESTMENTS_SUCCESS';

export const FETCH_INVESTMENTS_FAILURE = 'FETCH_INVESTMENTS_FAILURE';

export const SET_PERIOD_SELECTED = 'SET_PERIOD_SELECTED';
